// Code generated by MockGen. DO NOT EDIT.
// Source: get.go
//
// Generated by this command:
//
//	mockgen --source=get.go --destination=../../../mocks/service/httpreq/httpreq.go
//

// Package mock_httpreq is a generated GoMock package.
package mock_httpreq

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpReqService is a mock of HttpReqService interface.
type MockHttpReqService struct {
	ctrl     *gomock.Controller
	recorder *MockHttpReqServiceMockRecorder
	isgomock struct{}
}

// MockHttpReqServiceMockRecorder is the mock recorder for MockHttpReqService.
type MockHttpReqServiceMockRecorder struct {
	mock *MockHttpReqService
}

// NewMockHttpReqService creates a new mock instance.
func NewMockHttpReqService(ctrl *gomock.Controller) *MockHttpReqService {
	mock := &MockHttpReqService{ctrl: ctrl}
	mock.recorder = &MockHttpReqServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpReqService) EXPECT() *MockHttpReqServiceMockRecorder {
	return m.recorder
}

// ECSMetadata mocks base method.
func (m *MockHttpReqService) ECSMetadata() (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ECSMetadata")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ECSMetadata indicates an expected call of ECSMetadata.
func (mr *MockHttpReqServiceMockRecorder) ECSMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ECSMetadata", reflect.TypeOf((*MockHttpReqService)(nil).ECSMetadata))
}

// FluentBitHealth mocks base method.
func (m *MockHttpReqService) FluentBitHealth() (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FluentBitHealth")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FluentBitHealth indicates an expected call of FluentBitHealth.
func (mr *MockHttpReqServiceMockRecorder) FluentBitHealth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FluentBitHealth", reflect.TypeOf((*MockHttpReqService)(nil).FluentBitHealth))
}

// SgAPI mocks base method.
func (m *MockHttpReqService) SgAPI() (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SgAPI")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SgAPI indicates an expected call of SgAPI.
func (mr *MockHttpReqServiceMockRecorder) SgAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SgAPI", reflect.TypeOf((*MockHttpReqService)(nil).SgAPI))
}
