on:
  push:
    tags: "v*"
  workflow_dispatch:

permissions:
  content: write

jobs:
  download-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install gh -y

      - name: Download asset from latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status
          gh release download \
            --repo StackGuardian/golang-runner-service \
            --pattern 'golang-runner-service_Linux_x86_64.tar.gz' \
            --dir ./downloaded-assets
      
      - name: combine files in a directory
        run: |
          mkdir combined
          cp main.sh ./combined/main.sh
          cp downloaded-assets/sgrunner ./combined/assests
          ls
          ls combined

      - name: Determine if prerelease
        id: check_prerelease
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if [[ "$TAG_NAME" == *-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}