// Code generated by MockGen. DO NOT EDIT.
// Source: system.go
//
// Generated by this command:
//
//	mockgen -source=system.go -destination=../../../mocks/service/system/mock_system.go
//

// Package mock_system is a generated GoMock package.
package mock_system

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemService is a mock of SystemService interface.
type MockSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockSystemServiceMockRecorder
	isgomock struct{}
}

// MockSystemServiceMockRecorder is the mock recorder for MockSystemService.
type MockSystemServiceMockRecorder struct {
	mock *MockSystemService
}

// NewMockSystemService creates a new mock instance.
func NewMockSystemService(ctrl *gomock.Controller) *MockSystemService {
	mock := &MockSystemService{ctrl: ctrl}
	mock.recorder = &MockSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemService) EXPECT() *MockSystemServiceMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockSystemService) Command(cmd []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Command indicates an expected call of Command.
func (mr *MockSystemServiceMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockSystemService)(nil).Command), cmd)
}

// SystemdServiceStatus mocks base method.
func (m *MockSystemService) SystemdServiceStatus(service string) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemdServiceStatus", service)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SystemdServiceStatus indicates an expected call of SystemdServiceStatus.
func (mr *MockSystemServiceMockRecorder) SystemdServiceStatus(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemdServiceStatus", reflect.TypeOf((*MockSystemService)(nil).SystemdServiceStatus), service)
}
