// Code generated by MockGen. DO NOT EDIT.
// Source: system.go
//
// Generated by this command:
//
//	mockgen -source=system.go -destination=../../../mocks/service/system/mock_system.go
//

// Package mock_system is a generated GoMock package.
package mock_system

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemService is a mock of SystemService interface.
type MockSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockSystemServiceMockRecorder
	isgomock struct{}
}

// MockSystemServiceMockRecorder is the mock recorder for MockSystemService.
type MockSystemServiceMockRecorder struct {
	mock *MockSystemService
}

// NewMockSystemService creates a new mock instance.
func NewMockSystemService(ctrl *gomock.Controller) *MockSystemService {
	mock := &MockSystemService{ctrl: ctrl}
	mock.recorder = &MockSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemService) EXPECT() *MockSystemServiceMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockSystemService) Command(cmd []string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Command", cmd)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Command indicates an expected call of Command.
func (mr *MockSystemServiceMockRecorder) Command(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockSystemService)(nil).Command), cmd)
}

// SystemdServicesStatusAND mocks base method.
func (m *MockSystemService) SystemdServicesStatusAND(systemdServices []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemdServicesStatusAND", systemdServices)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemdServicesStatusAND indicates an expected call of SystemdServicesStatusAND.
func (mr *MockSystemServiceMockRecorder) SystemdServicesStatusAND(systemdServices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemdServicesStatusAND", reflect.TypeOf((*MockSystemService)(nil).SystemdServicesStatusAND), systemdServices)
}
